services:
  - type: web
    name: trashverse-backend
    env: python
    plan: starter
    buildCommand: chmod +x build.sh && ./build.sh
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SECRET_KEY
        generateValue: true
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: DATABASE_URL
        value: postgresql://postgres:[YOUR-SUPABASE-PASSWORD]@db.gtieccjexcvgrqhbwosd.supabase.co:5432/postgres
      - key: SUPABASE_PROJECT_URL
        value: https://gtieccjexcvgrqhbwosd.supabase.co
      - key: SUPABASE_ANON_KEY
        value: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd0aWVjY2pleGN2Z3JxaGJ3b3NkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ3NDU4NzAsImV4cCI6MjA5MDMyMTg3MH0.K5Uhdhn9CDr-FKoFVbGVkN9-KX4ZmDlinyAxSzjello
      - key: FIREBASE_CREDENTIALS_PATH
        value: ./firebase-credentials.json
      - key: RESEND_API_KEY
        value: re_imeqaLTJ_LMycHLq3YEs1R9XAiHqD9VvW
      - key: DEFAULT_FROM_EMAIL
        value: onboarding@resend.dev
      - key: PASSWORD_RESET_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: EMAIL_MODE
        value: production
      - key: DEV_EMAIL_RECIPIENT
        value: onyewuchiscepter@gmail.com
      - key: ENVIRONMENT
        value: production