services:
  - type: web
    name: trashverse-backend
    env: python
    region: oregon
    plan: free
    branch: main
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app.main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:$PORT
    envVars:
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: trashverse-db
          property: connectionString
      - key: SUPABASE_PROJECT_URL
        sync: false
      - key: SUPABASE_ANON_KEY
        sync: false
      - key: RESEND_API_KEY
        sync: false
      - key: DEFAULT_FROM_EMAIL
        value: onboarding@resend.dev
      - key: EMAIL_MODE
        value: production
      - key: ENVIRONMENT
        value: production
      - key: ALGORITHM
        value: HS256
      - key: ACCESS_TOKEN_EXPIRE_MINUTES
        value: 10080
      - key: PASSWORD_RESET_TOKEN_EXPIRE_MINUTES
        value: 30
      - key: ALLOWED_ORIGINS
        value: https://trashverse.netlify.app,http://localhost:3002

databases:
  - name: trashverse-db
    databaseName: trashverse
    user: trashverse
    plan: free
