export const nigeriaData = {
  Enugu: [
    "Enugu East",
    "Enugu West",
    "Enugu North",
    "Nsukka",
    "Udi",
    "Oji River",
    "Igbo Etiti",
    "Igbo Eze North",
    "Igbo Eze South",
  ],
  Lagos: [
    "Ikeja",
    "Surulere",
    "Yaba",
    "Ikorodu",
    "Epe",
    "Lekki",
  ],
  Abuja: [
    "Gwagwalada",
    "Kuje",
    "Abaji",
    "Bwari",
    "Kwali",
  ],
  Abia: [
    "Aba North",
    "Aba South",
    "Umuahia North",
    "Umuahia South",
    "Isiala Ngwa North",
    "Isiala Ngwa South",
    "Obingwa",
    "Ukwa East",
    "Ukwa West",
    "Ikwuano",
    "Ohafia",
    "Arochukwu",
    "Bende",
    "Osisioma Ngwa",
    "Ugwunagbo",
    "Isuikwuato",
    "Umunneochi",
  ],
};